### ISSUE TITLE
Please remove inputs 

### ISSUE THREAD

**Issue by StefanWetterActiware** [fuglede/adventofcode#7]
Hey there,
AOC states, you should not publish your inputs.
Please remove them.
Thanks!

Great work!

regards
Stefan

**Comment by fuglede** [comment]
Wastl mentioned at some point something along the lines of posting inputs being fine as long as it doesn't turn into a scraping exercise. I left them in here because what often happens is that the input ends up being an actual part of the puzzle (the one on Fourier transforms comes to mind), and every now and then the solutions I provide will make assumptions about the input that aren't necessarily true for all inputs belonging to the natural class of inputs for any given puzzle, or even to the set of inputs available to others.
